### PR TITLE
test: install driver during migration job

### PR DESCRIPTION
**Pull request by chewong**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Depends on https://github.com/kubernetes/test-infra/pull/16590.
/hold
/assign @andyzhangx 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by chewong** [comment]
/unhold
@andyzhangx PTAL

**Comment by andyzhangx** [comment]
Great!
And I have add migration kubelet flag in migration.json and also added some logging in e2e test, the migration e2e test pass in `1.18.0-beta.1`

**Comment by andyzhangx** [comment]
so next plan is enable migration test on azure file driver, thanks!

**Pull request merged**
