### PR TITLE
[V2] chore: add parse max shares unit test

### PR DESCRIPTION
**Pull request by NedAnd1**
**What type of PR is this?**

/kind test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by landreasyan** [comment]
Looking at the `GetMaxShares` and `ParseMaxShares` implementations highlighted by this PR, I noticed that there is a bit of code duplication. Can we also have `GetMaxShares` call `ParseMaxShares` instead of duplicating the logic? In that case we can have different unit tests for each of those methods, `ParseMaxShares` will be tested like we do now, but for `GetMaxShares` we should pass invalid attributes array and check that function handles that properly instead of checking the string to int parsing.

**Comment by edreed** [comment]
> Looking at the `GetMaxShares` and `ParseMaxShares` implementations highlighted by this PR, I noticed that there is a bit of code duplication. Can we also have `GetMaxShares` call `ParseMaxShares` instead of duplicating the logic? In that case we can have different unit tests for each of those methods, `ParseMaxShares` will be tested like we do now, but for `GetMaxShares` we should pass invalid attributes array and check that function handles that properly instead of checking the string to int parsing.

@landreasyan The change you propose was already made in #1754.

**Comment by landreasyan** [comment]
> > Looking at the `GetMaxShares` and `ParseMaxShares` implementations highlighted by this PR, I noticed that there is a bit of code duplication. Can we also have `GetMaxShares` call `ParseMaxShares` instead of duplicating the logic? In that case we can have different unit tests for each of those methods, `ParseMaxShares` will be tested like we do now, but for `GetMaxShares` we should pass invalid attributes array and check that function handles that properly instead of checking the string to int parsing.
> 
> @landreasyan The change you propose was already made in #1754.

Oh, I see, that is great! Although the change in the unit tests I was proposing is not done. We still have unit tests for `GetMaxShares` and `ParseMaxShares` that check the same thing.

**Comment by NedAnd1** [comment]
> > > Looking at the `GetMaxShares` and `ParseMaxShares` implementations highlighted by this PR, I noticed that there is a bit of code duplication. Can we also have `GetMaxShares` call `ParseMaxShares` instead of duplicating the logic? In that case we can have different unit tests for each of those methods, `ParseMaxShares` will be tested like we do now, but for `GetMaxShares` we should pass invalid attributes array and check that function handles that properly instead of checking the string to int parsing.
> > 
> > 
> > @landreasyan The change you propose was already made in #1754.
> 
> Oh, I see, that is great! Although the change in the unit tests I was proposing is not done. We still have unit tests for `GetMaxShares` and `ParseMaxShares` that check the same thing.

@landreasyan Thanks for the feedback; I made your suggested changes, and hopefully it looks good.

**Comment by edreed** [comment]
The test failure is unrelated to this change.

**Pull request merged**
