### PR TITLE
test: enable one windows test for CSI driver

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
test: enable one windows test for CSI driver

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by jsafrane** [comment]
Is this test working? It did not pass in https://github.com/kubernetes/kubernetes/pull/94916 / https://testgrid.k8s.io/provider-azure-presubmit#pr-k8s-azure-disk-e2e-master-windows and the PR looks unrelated.

**Comment by andyzhangx** [comment]
> Is this test working? It did not pass in [kubernetes/kubernetes#94916](https://github.com/kubernetes/kubernetes/pull/94916) / https://testgrid.k8s.io/provider-azure-presubmit#pr-k8s-azure-disk-e2e-master-windows and the PR looks unrelated.

@jsafrane I am now trying to fix this test case: `should create a deployment object, write and read to it, delete the pod and write and read to it again`, if I cannot fix this failure today, I will disable it first, thanks.

**Comment by andyzhangx** [comment]
@jsafrane this PR(https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/569) may fix that issue, need a few test run.

**Comment by smileusd** [comment]
Thanks @jsafrane @andyzhangx

**Pull request merged**
