### PR TITLE
Refactor: move flags definition to config functions

### PR DESCRIPTION
**Pull request by MartinForReal**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Refactor: move flags definition to config functions
move initialization code to NewDriver func
**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:
nodeid check is moved to DriverCore factory method. 
expose metrics function is moved to DriverCore.Run()

**Release note**:
```
none
```

### CODE REVIEW

**Comment by MartinForReal** [comment]
[blocked by #](https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2124)

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
