### PR TITLE
Add AZURE prefix to e2e environment variables

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/459

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:
/hold

I need to go through all the repos that rely on these values.

**Release note**:
```
Add AZURE prefix to e2e environment variables
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/retest

this job seems quite flaky looking at the job history...

**Comment by andyzhangx** [comment]
> /retest
> 
> this job seems quite flaky looking at the job history...

yep, as I could see for this failure, the underlying windows test infra is not stable:
```
Events:
  Type     Reason          Age   From               Message
  ----     ------          ----  ----               -------
  Normal   Scheduled       60m   default-scheduler  Successfully assigned kube-system/csi-azuredisk-node-win-2jpn2 to 3302k8s001
  Warning  FailedMount     60m   kubelet            MountVolume.SetUp failed for volume "csi-azuredisk-node-sa-token-tml6m" : failed to sync secret cache: timed out waiting for the condition
```

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
/hold cancel
/retest

**Pull request merged**
