### PR TITLE
feat: buildx windows with os.version

### LINKED ISSUE #519: buildx windows support doenst include os.version
```shell
docker buildx build --no-cache -t $(IMAGE_TAG)-linux-amd64 -f ./pkg/azurediskplugin/Dockerfile --platform="linux/amd64" --push .
docker buildx build --no-cache -t $(IMAGE_TAG)-windows-1809-amd64 -f ./pkg/azurediskplugin/Windows.Dockerfile --platform="windows/amd64" --push .
docker manifest create $(IMAGE_TAG) $(IMAGE_TAG)-linux-amd64 $(IMAGE_TAG)-windows-1809-amd64
docker manifest inspect $(IMAGE_TAG)
```

windows uses a key called os.version in the manifest to know which image to run for a particular manifest. When an image is created with buildx that information is missing and subsequently not added to the manifest when you run the `docker manifest create` command. You have to add this information manually.

Update:
    I see there is the reason why need os.version:

For Windows containers without Hyper-V isolation, the host OS Version and the Container OS Version need to match, which is why we added multiple Windows OS Versions to the building process.

Adds support for Windows OS Versions: 1809, 1903, 1909, 2004.
https://github.com/kubernetes/kubernetes/pull/91452

related issue: https://github.com/docker/cli/issues/2722

### PR DESCRIPTION
**Pull request by Sakuralbj**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #519 

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
could you paste out the manifest result with this PR?

**Comment by Sakuralbj** [comment]
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 953,
         "digest": "sha256:f763befd848934f59d7eab666bb50cfc7b844add01cebc579e7b71bfb58bf941",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 951,
         "digest": "sha256:18539910c200baf5623d160c11dfa5183e9cffce2d9348f94a9de103279e2d0d",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.1457"
         }
      }
   ]
}
```

**Comment by andyzhangx** [comment]
> ```
> docker manifest inspect sakuralbj/azuredisk-csi:v0.10.0
> {
>    "schemaVersion": 2,
>    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
>    "manifests": [
>       {
>          "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
>          "size": 953,
>          "digest": "sha256:f763befd848934f59d7eab666bb50cfc7b844add01cebc579e7b71bfb58bf941",
>          "platform": {
>             "architecture": "amd64",
>             "os": "linux"
>          }
>       },
>       {
>          "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
>          "size": 951,
>          "digest": "sha256:18539910c200baf5623d160c11dfa5183e9cffce2d9348f94a9de103279e2d0d",
>          "platform": {
>             "architecture": "amd64",
>             "os": "windows",
>             "os.version": "10.0.17763.1457"
>          }
>       }
>    ]
> }
> ```

how did you get this output? I cannot find `os.version` in CI test logs:
```
docker manifest inspect k8sprow.azurecr.io/azuredisk-csi:e2e-1226bc7d0e25903f51c5885b906807843f857bab
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 953,
         "digest": "sha256:53aa629f0ad0a8460e68dde30fc7228bb07103f736f7969d58bb6805a7bb8bef",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 951,
         "digest": "sha256:51707c8f81ac4779705da81e6793ffc528e1f0e3d099802a8d9814b3b5baa54b",
         "platform": {
            "architecture": "amd64",
            "os": "windows"
         }
      }
   ]
}
docker manifest push --purge k8sprow.azurecr.io/azuredisk-csi:e2e-1226bc7d0e25903f51c5885b906807843f857ba
```

And it looks like this PR is not integrated with our image build pipeline.

**Comment by andyzhangx** [comment]
@ZeroMagic 
there is sth. wrong with the script
```
	case "echo 'hello world' >> /mnt/test-1/data && while true; do sleep 3600; done":
		return "echo hello world>> C:\\mnt\\test-1\\data.txt& FOR /L %N IN () DO timeout 3600"
```
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/538/pull-azuredisk-csi-driver-e2e-windows/1305700025224925184/build-log.txt
```
Sep 15 03:43:40.365: INFO: Pod azuredisk-volume-tester-xwlc7-0 has the following logs: 
C:\>timeout 3600 
timeout: can't execute '3600': No such file or directory

C:\>timeout 3600 
timeout: can't execute '3600': No such file or directory

C:\>timeout 3600 
timeout: can't execute '3600': No such file or directory

C:\>timeout 3600 
timeout: can't execute '3600': No such file or directory

C:\>timeout 3600 
timeout: can't execute '3600': No such file or directory

C:\>timeout 3600 
timeout: can't execute '3600': No such file or directory

```

**Comment by Sakuralbj** [comment]
> > ```
> > docker manifest inspect sakuralbj/azuredisk-csi:v0.10.0
> > {
> >    "schemaVersion": 2,
> >    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
> >    "manifests": [
> >       {
> >          "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
> >          "size": 953,
> >          "digest": "sha256:f763befd848934f59d7eab666bb50cfc7b844add01cebc579e7b71bfb58bf941",
> >          "platform": {
> >             "architecture": "amd64",
> >             "os": "linux"
> >          }
> >       },
> >       {
> >          "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
> >          "size": 951,
> >          "digest": "sha256:18539910c200baf5623d160c11dfa5183e9cffce2d9348f94a9de103279e2d0d",
> >          "platform": {
> >             "architecture": "amd64",
> >             "os": "windows",
> >             "os.version": "10.0.17763.1457"
> >          }
> >       }
> >    ]
> > }
> > ```
> 
> how did you get this output? I cannot find `os.version` in CI test logs:
> 
> ```
> docker manifest inspect k8sprow.azurecr.io/azuredisk-csi:e2e-1226bc7d0e25903f51c5885b906807843f857bab
> {
>    "schemaVersion": 2,
>    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
>    "manifests": [
>       {
>          "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
>          "size": 953,
>          "digest": "sha256:53aa629f0ad0a8460e68dde30fc7228bb07103f736f7969d58bb6805a7bb8bef",
>          "platform": {
>             "architecture": "amd64",
>             "os": "linux"
>          }
>       },
>       {
>          "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
>          "size": 951,
>          "digest": "sha256:51707c8f81ac4779705da81e6793ffc528e1f0e3d099802a8d9814b3b5baa54b",
>          "platform": {
>             "architecture": "amd64",
>             "os": "windows"
>          }
>       }
>    ]
> }
> docker manifest push --purge k8sprow.azurecr.io/azuredisk-csi:e2e-1226bc7d0e25903f51c5885b906807843f857ba
> ```
> 
> And it looks like this PR is not integrated with our image build pipeline.
> https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/538/pull-azuredisk-csi-driver-e2e-multi-az/1305700025229119491/build-log.txt

make manifest

**Comment by andyzhangx** [comment]
we use following commands to build image and `make e2e-bootstrap` to run e2e tests:
```console
make azuredisk-container
make push
make push-latest
```

so `make manifest` should be integrated with above commands: `make azuredisk-container` & `make e2e-bootstrap`, otherwise it's running out side of CI and image building process.

**Comment by Sakuralbj** [comment]
The manifest local address tested in prow is wrong. Have you encountered similar problem? 
```
os_version=1809
++ suffix=windows-amd64-1809
++ docker manifest annotate --os windows --arch amd64 k8sprow.azurecr.io/azuredisk-csi:e2e-e138f08a3d7b581134d8477f024c486cef74886c k8sprow.azurecr.io/azuredisk-csi:e2e-e138f08a3d7b581134d8477f024c486cef74886c-windows-amd64-1809
++ [[ windows = \w\i\n\d\o\w\s ]]
+++ getBaseImage windows/amd64/1809
+++ os_arch=windows/amd64/1809
+++ file=BASEIMAGE
+++ grep windows/amd64/1809= BASEIMAGE
+++ cut -d= -f2
++ BASEIMAGE=mcr.microsoft.com/windows/servercore:1809
+++ docker manifest inspect mcr.microsoft.com/windows/servercore:1809
+++ grep os.version
+++ head -n 1
+++ awk '{print $2}'
++ full_version='"10.0.17763.1457"'
++ sed -i -r 's/("os"\:"windows")/\0,"os.version":"10.0.17763.1457"/' /root/.docker/manifests/docker.io_k8sprow.azurecr.io_azuredisk-csi-e2e-e138f08a3d7b581134d8477f024c486cef74886c/docker.io_k8sprow.azurecr.io_azuredisk-csi-e2e-e138f08a3d7b581134d8477f024c486cef74886c-windows-amd64-1809
sed: can't read /root/.docker/manifests/docker.io_k8sprow.azurecr.io_azuredisk-csi-e2e-e138f08a3d7b581134d8477f024c486cef74886c/docker.io_k8sprow.azurecr.io_azuredisk-csi-e2e-e138f08a3d7b581134d8477f024c486cef74886c-windows-amd64-1809: No such file or directory
```
[https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docker/build.sh#L133](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docker/build.sh#L133)

[https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/538/pull-azuredisk-csi-driver-e2e-migration/1306100450793099264#1:build-log.txt%3A687](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/538/pull-azuredisk-csi-driver-e2e-migration/1306100450793099264#1:build-log.txt%3A687)

**Comment by andyzhangx** [comment]
fixed by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/585

**Pull request closed without merging**
