### PR TITLE
feat: support tags in snapshot

### LINKED ISSUE #358: Support for tags parameter in VolumeSnapshotClass
We have policy set to only allow the resources to be created with some specific tags.
We can create the pv with below tags added in storageclass. 
parameters:
  ...
  tags: 'TicketURL=*****'

But when create snapshot, it failed to pass the policy after we added the tags in the volumesnapshotclass.

Can we support to add tags in snapshot.

Azure csi version: v0.6.0
Kubernetes version: v1.17.4

### PR DESCRIPTION
**Pull request by ZeroMagic**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
support tags in snapshot

**Which issue(s) this PR fixes**:

Fixes #358

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by ZeroMagic** [comment]
/cc @celiawa
Via `parameters` fields in `storageclass-azuredisk-snapshot.yaml`, we can add the tags in snapshot.

**Comment by andyzhangx** [comment]
`pull-azuredisk-csi-driver-e2e-windows` test is broken?

**Comment by ZeroMagic** [comment]
> `pull-azuredisk-csi-driver-e2e-windows` test is broken?

Just becasue of network problem. It is successful now.

**Pull request merged**
