### PR TITLE
Make GO111MODULE on by default in Makefile

### PR DESCRIPTION
**Pull request by Jiawei0227**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This turns on GO111MODULE by default in the Makefile.

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
looks like need to set this flag in sanity test:
```
/home/prow/go/src/github.com/kubernetes-csi/csi-test/cmd/csi-sanity /home/prow/go/src/github.com/kubernetes-csi /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver
make[1]: Entering directory '/home/prow/go/src/github.com/kubernetes-csi/csi-test/cmd/csi-sanity'
go test -ldflags "-w -X github.com/kubernetes-csi/csi-test/cmd/csi-sanity.VERSION=v1.1.0-172-g82b0519-HEAD -extldflags '-z relro -z now'" -c -o csi-sanity
go: cannot find main module, but found Gopkg.lock in /home/prow/go/src/github.com/kubernetes-csi/csi-test
	to create a module there, run:
	cd ../.. && go mod init
make[1]: *** [Makefile:26: csi-sanity] Error 1
make[1]: Leaving directory '/home/prow/go/src/github.com/kubernetes-csi/csi-test/cmd/csi-sanity'
/home/prow/go/src/github.com/kubernetes-csi /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver
/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver
Begin to run sanity test...
test/sanity/run-test.sh: line 38: csi-sanity: command not found
pkill -f azurediskplugin
Deleting CSI sanity test binary
    sanity_test.go:89: Sanity test failed exit status 127
``

**Comment by Jiawei0227** [comment]
Sorry, which flag need to be set where?

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
