### PR TITLE
Windows support - set 1 - preparation

### PR DESCRIPTION
**Pull request by kkmsft**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test

 /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR prepares the code for the windows support. 
Following are the changes:
- Separate out Linux and Windows mounter.
- Add default filesystem for windows as "ntfs"
- Add unimplemented CSIProxyMounter for windows which will be used to contact csi-proxy (https://github.com/kubernetes-csi/csi-proxy).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by andyzhangx** [comment]
hi @chewong could you take a look at the pull-azuredisk-csi-driver-verify failure? thanks

**Comment by chewong** [comment]
You will need to make the following change in verify-golint.sh - https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/180/files#diff-b0d614af997e9303b204e4a406546bd9

**Pull request merged**
