### PR TITLE
test: add snapshot controller image version check

### LINKED ISSUE #387: add snapshot controller image version check in verify-helm-chart.sh
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

add snapshot controller image version check in verify-helm-chart.sh
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/csi-snapshot-controller.yaml

there is only csi-snapshotter image check:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/c0f3d536b9dd984776c1d23675e918da93a83111/hack/verify-helm-chart.sh#L46

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by ZeroMagic**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #387 

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@chewong do you know any change on `azure-cli-2.2.0` installation change:
```
ERROR: azure-cli-core 2.2.0 has requirement knack~=0.6.2, but you'll have knack 0.7.0 which is incompatible.
```

It depends on knack>=0.6.3, while finally it would download knack-0.7.0, maybe we should upgrade azure-cli-core version.
```
Collecting knack>=0.6.3,~=0.6
  Downloading knack-0.7.0.tar.gz (67 kB)
```

**Comment by chewong** [comment]
> @chewong do you know any change on `azure-cli-2.2.0` installation change:
> 
> ```
> ERROR: azure-cli-core 2.2.0 has requirement knack~=0.6.2, but you'll have knack 0.7.0 which is incompatible.
> ```
> 
> It depends on knack>=0.6.3, while finally it would download knack-0.7.0, maybe we should upgrade azure-cli-core version.
> 
> ```
> Collecting knack>=0.6.3,~=0.6
>   Downloading knack-0.7.0.tar.gz (67 kB)
> ```
> 
> https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/394/pull-azuredisk-csi-driver-e2e-single-az/1258753702378868737/build-log.txt

Looks like there is an issue when installing azure-cli with pip. Opened https://github.com/kubernetes/test-infra/pull/17564 so we install azure-cli using `apt-get`.

**Pull request merged**
