### PR TITLE
Do not install golangci-lint with 'go get'

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
/kind flake 

**What this PR does / why we need it**:
Currently the go get for golangci-lint is failing with:
```
$ go get github.com/golangci/golangci-lint/cmd/golangci-lint
# github.com/golangci/golangci-lint/pkg/golinters
go/src/github.com/golangci/golangci-lint/pkg/golinters/golint.go:21:14: l.LintPkg undefined (type *"github.com/golangci/lint-1".Linter has no field or method LintPkg)
go/src/github.com/golangci/golangci-lint/pkg/golinters/gomnd.go:13:6: cannot use magic_numbers.Analyzer (type *"github.com/tommy-muehle/go-mnd/vendor/golang.org/x/tools/go/analysis".Analyzer) as type *"golang.org/x/tools/go/analysis".Analyzer in array or slice literal
```

The README.md of golangci-lint recommends to do not use go get for installation - https://github.com/golangci/golangci-lint#go.

This PR also pins the golangci-lint version to a stable one - v1.24.0.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
cc @andyzhangx for `ok-to-test`

**Comment by andyzhangx** [comment]
/ok-to-test
actually I have worked out another PR: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/370
let's see which one works

**Pull request merged**
