### PR TITLE
target Azure Stack APIs

### PR DESCRIPTION
**Pull request by niachary**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes # API version changes

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by niachary** [comment]
PR created for testing if API versions are supported on global Azure. Closing the PR.

**Comment by andyzhangx** [comment]
for disk detach not supported issue on Azure stack, pls try this patch, and make sure `cloud.Environment.Name == "AZURESTACKCLOUD"`
```
diff --git a/vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_standard.go b/vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_standard.go
index 54ca4f8..e1c374e 100644
--- a/vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_standard.go
+++ b/vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_standard.go
@@ -142,7 +142,11 @@ func (as *availabilitySet) DetachDisk(diskName, diskURI string, nodeName types.N
                        (disk.ManagedDisk != nil && diskURI != "" && strings.EqualFold(*disk.ManagedDisk.ID, diskURI)) {
                        // found the disk
                        klog.V(2).Infof("azureDisk - detach disk: name %q uri %q", diskName, diskURI)
-                       disks[i].ToBeDetached = to.BoolPtr(true)
+                       if as.cloud.Environment.Name == "AZURESTACKCLOUD" {
+                               disks = append(disks[:i], disks[i+1:]...)
+                       } else {
+                               disks[i].ToBeDetached = to.BoolPtr(true)
+                       }
                        bFoundDisk = true
                        break
                }
diff --git a/vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go b/vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go
index 344e4f0..ba25ad6 100644
--- a/vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go
+++ b/vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go
@@ -147,7 +147,11 @@ func (ss *scaleSet) DetachDisk(diskName, diskURI string, nodeName types.NodeName
                        (disk.ManagedDisk != nil && diskURI != "" && strings.EqualFold(*disk.ManagedDisk.ID, diskURI)) {
                        // found the disk
                        klog.V(2).Infof("azureDisk - detach disk: name %q uri %q", diskName, diskURI)
-                       disks[i].ToBeDetached = to.BoolPtr(true)
+                       if ss.cloud.Environment.Name == "AZURESTACKCLOUD" {
+                               disks = append(disks[:i], disks[i+1:]...)
+                       } else {
+                               disks[i].ToBeDetached = to.BoolPtr(true)
+                       }
                        bFoundDisk = true
                        break
                }
```

**Comment by andyzhangx** [comment]
cc @jadarsie

**Pull request closed without merging**
