### PR TITLE
fix:   Fix default Docker Hub prefix generation.

### LINKED ISSUE #630: Fix default Docker registry prefix generation for `make push-manifest`
**What happened**:

Using `make push-manifest` to publish private images to my personal Docker Hub repository fails with the following error:

```
$ export REGISTRY=ejreed
$ export IMAGE_VERSION=latest
$ make push-manifest
docker manifest create --amend ejreed/azuredisk-csi:latest  ejreed/azuredisk-csi:latest-linux-amd64  ejreed/azuredisk-csi:latest-windows-1809-amd64  ejreed/azuredisk-csi:latest-windows-1903-amd64  ejreed/azuredisk-csi:latest-windows-1909-amd64  ejreed/azuredisk-csi:latest-windows-2004-amd64
Created manifest list docker.io/ejreed/azuredisk-csi:latest
# add "os.version" field to windows images (based on https://github.com/kubernetes/kubernetes/blob/master/build/pause/Makefile)
set -x; \
registry_prefix=; \
manifest_image_folder=`echo "${registry_prefix}ejreed/azuredisk-csi:latest" | sed "s|/|_|g" | sed "s/:/-/"`; \
for arch in amd64; do \
	for osversion in 1809 1903 1909 2004; do \
		BASEIMAGE=mcr.microsoft.com/windows/nanoserver:${osversion}; \
		full_version=`docker manifest inspect ${BASEIMAGE} | jq -r '.manifests[0].platform["os.version"]'`; \
		sed -i -r "s/(\"os\"\:\"windows\")/\0,\"os.version\":\"${full_version}\"/" "/home/edreed/.docker/manifests/${manifest_image_folder}/${manifest_image_folder}-windows-${osversion}-${arch}"; \
	done; \
done
+ registry_prefix=
+ echo ejreed/azuredisk-csi:latest
+ sed s|/|_|g
+ sed s/:/-/
+ manifest_image_folder=ejreed_azuredisk-csi-latest
+ BASEIMAGE=mcr.microsoft.com/windows/nanoserver:1809
+ docker manifest inspect mcr.microsoft.com/windows/nanoserver:1809
+ jq -r .manifests[0].platform["os.version"]
+ full_version=10.0.17763.1637
+ sed -i -r s/("os"\:"windows")/\0,"os.version":"10.0.17763.1637"/ /home/edreed/.docker/manifests/ejreed_azuredisk-csi-latest/ejreed_azuredisk-csi-latest-windows-1809-amd64
sed: can't read /home/edreed/.docker/manifests/ejreed_azuredisk-csi-latest/ejreed_azuredisk-csi-latest-windows-1809-amd64: No such file or directory
+ BASEIMAGE=mcr.microsoft.com/windows/nanoserver:1903
+ docker manifest inspect mcr.microsoft.com/windows/nanoserver:1903
+ jq -r .manifests[0].platform["os.version"]
+ full_version=10.0.18362.1256
+ sed -i -r s/("os"\:"windows")/\0,"os.version":"10.0.18362.1256"/ /home/edreed/.docker/manifests/ejreed_azuredisk-csi-latest/ejreed_azuredisk-csi-latest-windows-1903-amd64
sed: can't read /home/edreed/.docker/manifests/ejreed_azuredisk-csi-latest/ejreed_azuredisk-csi-latest-windows-1903-amd64: No such file or directory
+ BASEIMAGE=mcr.microsoft.com/windows/nanoserver:1909
+ docker manifest inspect mcr.microsoft.com/windows/nanoserver:1909
+ jq -r .manifests[0].platform["os.version"]
+ full_version=10.0.18363.1256
+ sed -i -r s/("os"\:"windows")/\0,"os.version":"10.0.18363.1256"/ /home/edreed/.docker/manifests/ejreed_azuredisk-csi-latest/ejreed_azuredisk-csi-latest-windows-1909-amd64
sed: can't read /home/edreed/.docker/manifests/ejreed_azuredisk-csi-latest/ejreed_azuredisk-csi-latest-windows-1909-amd64: No such file or directory
+ BASEIMAGE=mcr.microsoft.com/windows/nanoserver:2004
+ docker manifest inspect mcr.microsoft.com/windows/nanoserver:2004
+ jq -r .manifests[0].platform["os.version"]
+ full_version=10.0.19041.685
+ sed -i -r s/("os"\:"windows")/\0,"os.version":"10.0.19041.685"/ /home/edreed/.docker/manifests/ejreed_azuredisk-csi-latest/ejreed_azuredisk-csi-latest-windows-2004-amd64
sed: can't read /home/edreed/.docker/manifests/ejreed_azuredisk-csi-latest/ejreed_azuredisk-csi-latest-windows-2004-amd64: No such file or directory
make: *** [Makefile:152: push-manifest] Error 2
```

**What you expected to happen**:

It should successfully generate the manifest and push to the target image label.

**How to reproduce it**:

See example above.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by edreed**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #630 

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by edreed** [comment]
So the test that didn't fail due to infrastructure failed because the registry name used by the test runner is "k8sprow.azurecr.io" which doesn't contain a '/', but should also not be prefixed with "docker.io/". It seems to me that the regex should be looking for the presence or either '.' or '/'. I'll give that a try.

**Comment by andyzhangx** [comment]
could you squash commits by `git rebase -i HEAD~2`? thanks.

**Comment by edreed** [comment]
Done. (I always wondered how to do squash commits. I always had ADO take care of it. :) )

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
