### PR TITLE
Chores:bump dependencies to fix cve

### PR DESCRIPTION
**Pull request by MartinForReal**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Chores: bump dependencies to fix cve
replace github.com/pborman/uuid with k8s.io/apimachinery/pkg/util/uuid
**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by MartinForReal** [comment]
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2131

**Pull request merged**
