### PR TITLE
[V2] chore: Cut v2.0.0-beta.2 version

### PR DESCRIPTION
**Pull request by edreed**
**What type of PR is this?**

/kind chore

**What this PR does / why we need it**:

Cut v2.0.0-beta.2 version and switch main_v2 branch to 2.0.0-beta.3.

**Which issue(s) this PR fixes**:

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by nearora-msft** [comment]
Do we need this file : charts/v2.0.0-beta.2/azuredisk-csi-driver-v2.0.0-beta.1.tgz ?

**Comment by edreed** [comment]
> Do we need this file : charts/v2.0.0-beta.2/azuredisk-csi-driver-v2.0.0-beta.1.tgz ?

Nope. Removed.

**Comment by edreed** [comment]
> Do we also need to update the version here : https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/failover ?

Yes. Updated.

**Pull request merged**
