### PR TITLE
[V2] test: Enable test in windows

### PR DESCRIPTION
**Pull request by alice-zheyan-yu**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
Enable DynamicallyProvisionedVolumeSnapshotTest in Windows cluster.

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@alice-zheyan-yu could you also enable the same test in master branch for v1? thanks.

**Comment by alice-zheyan-yu** [comment]
> 

@andyzhangx It has been enabled in this PR: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1548

**Comment by andyzhangx** [comment]
@alice-zheyan-yu thanks for the effort!

**Comment by alice-zheyan-yu** [comment]
> @alice-zheyan-yu thanks for the effort!

@andyzhangx No problem

**Pull request merged**
