### PR TITLE
feat: add affinity and node affinity as values

### LINKED ISSUE #732: Chart Enhancement - tolerations, nodeSelector, resources
**Is your feature request related to a problem?/Why is this needed**

Please add options to configure tolerations, nodeSelector and resources blocks for pods launched by this chart. 

**Describe the solution you'd like in detail**

Standard public chart value options for customizing/configuring workloads in various cluster configurations.

See `helm create` for the standard helm chart template.

Will you accept a Pull Request to enhance the chart?

### PR DESCRIPTION
**Pull request by cyril-corbon**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
- [x] add node affinity as values in the helm chart for daemonset
- [x] add affinity to controller deployment

**Which issue(s) this PR fixes**:

Fixes #732 

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
could you update chart file `charts/latest/azuredisk-csi-driver-v1.7.0.tgz` first? thanks.

**Comment by cyril-corbon** [comment]
just done ! :smile:

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
