### PR TITLE
add create/delete/list snapshot feature

### LINKED ISSUE #25: [feature] add create/delete/list snapshot feature
https://kubernetes-csi.github.io/docs/snapshot-restore-feature.html#snapshot--restore-feature
related AKS feature request: https://github.com/Azure/AKS/issues/658

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR implements the standard CSI snapshot functionalities, including:
 - CreateSnapshot
 - ListSnapshots
 - DeleteSnapshot

This PR does not contain restore snapshot feature. It would be addressed next.

**Which issue(s) this PR fixes**:

Fixes #25

**Special notes for your reviewer**:

**Release note**:
```
add create/delete/list snapshot feature
```

### CODE REVIEW

**Comment by michael-niemand** [comment]
I just tried restoring a azuredisk-csi snapshot but it appeared to be empty. 

- snapshot went into ready to use state
- restore went through successfully
- restored PVC seemed empty when mounted into pod

Does this have something to do with the new snapshotter like in the azure-file-driver?

**Comment by andyzhangx** [comment]
> I just tried restoring an azuredisk-csi snapshot but it appeared to be empty.
> 
> * snapshot went into ready to use state
> * restore went through successfully
> * restored PVC seemed empty when mounted into pod
> 
> Does this have something to do with the new snapshotter like in the azure-file-driver?
> edit: using the master branch version of the driver and applied the "activate snapshot" script of the documentation; AKS 1.17.7

@ZeroMagic can you take a look at this issue? thanks

**Comment by ZeroMagic** [comment]
@michael-niemand I followed the [example doc](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/snapshot/README.md) to test with the master branch version on AKS 1.17.7. There is not something wrong. 

In addition, the snapshot related sidecar containers in azurefile-csi-driver are the same with azuredisk-csi-driver.
/cc @andyzhangx

**Comment by michael-niemand** [comment]
@ZeroMagic thank you so much for looking, I will need to investigate further for a user error I suppose. Is there anything I should be looking at in particular?

**Comment by ZeroMagic** [comment]
@michael-niemand  There are three points that I usually check when using the snapshot function. 

- k8s version >= 1.17.0

- Ensure the three CRDs are installed. `volumesnapshotclasses.snapshot.storage.k8s.io`, `volumesnapshotcontents.snapshot.storage.k8s.io` and `volumesnapshots.snapshot.storage.k8s.io`.

- Ensure the related RBACs are correct.  Refer to `azuredisk-external-provisioner-role` and `azuredisk-external-snapshotter-role` in [rbac-csi-azuredisk-controller.yaml](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml), `all roles` in [rbac-csi-snapshot-controller.yaml](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/charts/latest/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml).

**Comment by michael-niemand** [comment]
I cleaned up the drivers with the cleanup scripts (thx for those!!) and reinstalled; the snapshot is _not_ going through, but the error seems to be on our side. Just for anyone getting here via search engine: Reason for the error seems to be a Policy Violation Error (409):
`Failed to check and update snapshot content: rpc error: code = Internal desc = create snapshot error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: {"error":{"code":"ConflictingAppendPolicies","message":"Found conflicting policies that modify the same field. [...]`
I'm going to have to ask Ops for a fix.

**Comment by ZeroMagic** [comment]
Thanks for sharing the detail error info. It is an unkown error which we have never encountered.

**Pull request merged**
