### PR TITLE
fix: reduce GetDisk in AttachDisk

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: reduce GetDisk in AttachDisk
refer to https://github.com/kubernetes-sigs/cloud-provider-azure/pull/678 

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
fix: reduce GetDisk in AttachDisk
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by feiskyer** [comment]
@andyzhangx could you enable the coveralls github comments (like https://github.com/kubernetes-sigs/cloud-provider-azure/pull/678#issuecomment-869134858), so the unit test coverage is shown automatically in the PR?

**Comment by andyzhangx** [comment]
> @andyzhangx could you enable the coveralls github comments (like [kubernetes-sigs/cloud-provider-azure#678 (comment)](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/678#issuecomment-869134858)), so the unit test coverage is shown automatically in the PR?

@ZeroMagic do you know why it's broken? The code coverage code is actually copied from csi driver, did not figure out why only disk driver is broken, actually azure file, and blob csi drivers are all working.

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/05768a8f3fd61f3de75e002e0db7420057a3da46/.github/workflows/linux.yml#L20-L27

**Pull request merged**
