### PR TITLE
chore: upgrade csi-attacher to v2.2.0

### LINKED ISSUE #339: leader-election-type has been removed in csi attacher v2.x
**Is your feature request related to a problem?/Why is this needed**
I found that our attacher deploy yaml still includes [-leader-election-type](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/csi-azuredisk-controller.yaml#L59), it may works right now, since we're using v1.2.0, but It has been removed since v2.0, see [ref](https://github.com/kubernetes-csi/external-attacher/pull/173).

**Describe the solution you'd like in detail**
While we're prepared to upgrade the attacher version to v2.0, don't forget to remove this line. Otherwise, the csi attacher container would panic.

**Describe alternatives you've considered**
None.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
chore: upgrade csi-attacher to v2.2.0
To support `LIST_VOLUMES_PUBLISHED_NODES` capability

**Which issue(s) this PR fixes**:

Fixes #339

**Special notes for your reviewer**:
/hold
hold on, need to check whether csi-attacher `v2.2.0` supports v1.14 or not

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
/hold
hold on, need to check whether csi-attacher v2.0.0 supports v1.14 or not

**Comment by andyzhangx** [comment]
@Colstuwjx the csi-attacher in our CI test does not work(on v1.18.x), do you know what's the required change on this? thanks.
Strange thing is the new csi-attacher(`v2.0.0`) works on my k8s v1.16.7 cluster.

**Comment by Colstuwjx** [comment]
Which error do you see? I deployed on v1.15.3 and it works fine.

**Comment by Colstuwjx** [comment]
Do we have more detail log? I only can see sth like this:

```
Apr 26 02:36:38.697: INFO: At 2020-04-26 02:23:29 +0000 UTC - event for azuredisk-volume-tester-m265g: {attachdetach-controller } FailedAttachVolume: AttachVolume.Attach failed for volume "pvc-1fd29ca1-17fe-4b81-bfc2-379186ac6c6b" : attachdetachment timeout for volume /subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-a434ad63-8762-11ea-8b16-46f4cddcd295/providers/Microsoft.Compute/disks/pvc-1fd29ca1-17fe-4b81-bfc2-379186ac6c6b
```

Some related issue, for example, like [this](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/23), it seems that you choose a [workaround solution](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/23#issuecomment-502703648) by making much bigger timeout value.

I think we need to find out the root cause, why we need to wait more than 120s for attaching? it's NOT reasonable.

Thanks.

**Comment by andyzhangx** [comment]
> Do we have more detail log? I only can see sth like this:
> 
> ```
> Apr 26 02:36:38.697: INFO: At 2020-04-26 02:23:29 +0000 UTC - event for azuredisk-volume-tester-m265g: {attachdetach-controller } FailedAttachVolume: AttachVolume.Attach failed for volume "pvc-1fd29ca1-17fe-4b81-bfc2-379186ac6c6b" : attachdetachment timeout for volume /subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-a434ad63-8762-11ea-8b16-46f4cddcd295/providers/Microsoft.Compute/disks/pvc-1fd29ca1-17fe-4b81-bfc2-379186ac6c6b
> ```
> 
> Some related issue, for example, like [this](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/23), it seems that you choose a [workaround solution](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/23#issuecomment-502703648) by making much bigger timeout value.
> 
> I think we need to find out the root cause, why we need to wait more than 120s for attaching? it's NOT reasonable.
> 
> Thanks.

@Colstuwjx
I found the root cause, the rbac on "volumeattachments" on v1.18.0 needs `patch` permission, while 1.15, 1.16 don't need this:
```
I0426 11:52:18.153231       1 csi_handler.go:99] Error processing "csi-564ec37122908840e95d6149dcd4c9b3adb10c8d231f7fe16e7f57d2ac97bc59": failed to attach: could not save VolumeAttachment: volumeattachments.storage.k8s.io "csi-564ec37122908840e95d6149dcd4c9b3adb10c8d231f7fe16e7f57d2ac97bc59" is forbidden: User "system:serviceaccount:kube-system:csi-azuredisk-controller-sa" cannot patch resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope
```

**Comment by andyzhangx** [comment]
looks like transient error:
```
• Failure in Spec Teardown (AfterEach) [135.978 seconds]
Pre-Provisioned
/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning_test.go:38
  [single-az] [AfterEach]
  /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning_test.go:68
    should use a pre-provisioned volume and mount it as readOnly in a pod [disk.csi.azure.com]
    /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning_test.go:69

    create volume "/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-a2589232-87b5-11ea-841c-66d1387e8811/providers/Microsoft.Compute/disks/pre-provisioned-readOnly" error: Retriable: true, RetryAfter: 0s, HTTPStatusCode: 503, RawError: Retriable: true, RetryAfter: 0s, HTTPStatusCode: 503, RawError: {"error":{"code":"ServerTimeout","message":"The request timed out. Diagnostic information: timestamp '20200426T122516Z', subscription id '0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e', tracking id '24508c1d-aa2a-4444-984d-639324872b9c', request correlation id '24508c1d-aa2a-4444-984d-639324872b9c'."}}
```

**Pull request merged**
