### PR TITLE
fix: set minimum disk size as 1GiB

### LINKED ISSUE #592: Snapshot restore cannot handle less than 1 Gi
**What happened**:
I am running the k8s e2e snapshottable test againest Azuredisk csi driver. And the snapshot test failed because it failed to restore the snapshot to PVC. And I looked into what happened:

The PVC created by the e2e test is only 1 M, and when create snapshot, it seems azuredisk will automatically round up to 1G. So when trying to restore the PVC, the pvc will not be able to restored correctly.

I am wondering if 1G is the minimum snapshot size azuredisk can do?

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: set minimum disk size as 1GiB

**Which issue(s) this PR fixes**:

Fixes #592

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
fix: set minimum disk size as 1GiB
```

/assign @Jiawei0227

### CODE REVIEW

**Review by Jiawei0227 — APPROVED** [review]
/lgtm

**Comment by andyzhangx** [comment]
sigh, quite unstable windows test, manually merge it...

**Pull request merged**
