### PR TITLE
fix: windows e2e test helm install command

### PR DESCRIPTION
**Pull request by songjiaxun**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix helm install command for windows e2e test.

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by songjiaxun** [comment]
\assign @andyzhangx

**Review by andyzhangx — APPROVED** [review]
/ok-to-test
/lgtm
/approve

**Pull request merged**
