### PR TITLE
Add e2e test support for Windows clusters

### PR DESCRIPTION
**Pull request by chewong**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by andyzhangx** [comment]
thanks @chewong , I think we could add windows e2e tests first for in-tree driver, and once csi driver supports windows, then we could enable those tests for csi driver.

cc @ritazh @craiglpeters

**Comment by andyzhangx** [comment]
@chewong 
Since windows is now supported on master branch: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/windows, could you also enable windows e2e test for csi driver? I think the difficulty is how to build and push windows csi driver in e2e test.

cc @ZeroMagic

**Comment by chewong** [comment]
> @chewong
> Since windows is now supported on master branch: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/windows, could you also enable windows e2e test for csi driver? I think the difficulty is how to build and push windows csi driver in e2e test.
> 
> cc @ZeroMagic

Yes, I will be working on that. The blocker right now, as you mentioned, is that we can't build Windows containers in prow.

**Comment by andyzhangx** [comment]
> > @chewong
> > Since windows is now supported on master branch: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/windows, could you also enable windows e2e test for csi driver? I think the difficulty is how to build and push windows csi driver in e2e test.
> > cc @ZeroMagic
> 
> Yes, I will be working on that. The blocker right now, as you mentioned, is that we can't build Windows containers in prow.

@chewong One way is build `azurediskplugin.exe` in prow, and push to azure blob storage, and then set up a windows 1809 server to docker build and then push to ACR.

**Comment by chewong** [comment]
> > > @chewong
> > > Since windows is now supported on master branch: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/windows, could you also enable windows e2e test for csi driver? I think the difficulty is how to build and push windows csi driver in e2e test.
> > > cc @ZeroMagic
> > 
> > 
> > Yes, I will be working on that. The blocker right now, as you mentioned, is that we can't build Windows containers in prow.
> 
> @chewong One way is build `azurediskplugin.exe` in prow, and push to azure blob storage, and then set up a windows 1809 server to 1) download `azurediskplugin.exe` 2) docker build 3) push to ACR.

@ZeroMagic and I were thinking of building and pushing the Windows container to ACR with Travis CI since it supports Windows environment. We will run the Windows CSI driver e2e test assuming the image has been pushed by Travis CI. WDYT?

**Pull request merged**
