### PR TITLE
[V2] feat: creating workload manifest to use for workload tests

### PR DESCRIPTION
**Pull request by connorbradshaw10**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
creating workload manifest to use for workload tests

### CODE REVIEW

**Comment by edreed** [comment]
@connorbradshaw10 FYI- At some point soon, we need to switch over to using AKS cli to build out clusters testing. `aks-engine` is deprecated and will be out of support soon.

**Comment by connorbradshaw10** [comment]
> @connorbradshaw10 FYI- At some point soon, we need to switch over to using AKS cli to build out clusters testing. `aks-engine` is deprecated and will be out of support soon.

we are running everything on aks cli but using this template format and roughly translating it to aks cli by parsing some of the values

**Pull request merged**
