### PR TITLE
enhance(dep): adds prune options in gopkg.toml

### PR DESCRIPTION
**Pull request by ashishranjan738**
Signed-off-by: Ashish Ranjan <ashishranjan738@gmail.com>

**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it**:
-> This commit adds prune options in `gopkg.toml` which will remove unused packages and go tests. This help reducing vendor size.
-> This commit also contains changes of `dep ensure` after adding prune option.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/58

**Special notes for your reviewer**:

**Release note**:
```
reduce vendor package size by adding prune options in gopkg.toml
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@ashishranjan738 that's great! what's the ultimate size of vendor dir with this PR?

**Comment by ashishranjan738** [comment]
it got reduced from 530 MB to 47 MB

**Comment by ashishranjan738** [comment]
> @ashishranjan738 that's great! what's the ultimate size of vendor dir with this PR?



> @ashishranjan738 that's great! what's the ultimate size of vendor dir with this PR?

it got reduced from 530 MB to 47 MB

**Comment by ashishranjan738** [comment]
> @ashishranjan738 that's great! what's the ultimate size of vendor dir with this PR?

it got reduced from 530 MB to 47 MB

**Comment by andyzhangx** [comment]
thanks, could you also fix this issue in azure file driver:
https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/38

**Pull request merged**
