### PR TITLE
[V2] chore: upgrade cloud-provider-azure

### PR DESCRIPTION
**Pull request by edreed**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Upgrades `cloud-provider-azure` to the latest as of 2023-01-06.

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by edreed** [comment]
edreed/cloud-provider-azure#179 needs to be merged first and this PR updated to the master branch version.

/hold

**Comment by edreed** [comment]
edreed/cloud-provider-azure#179 has merged.

/unhold

**Review by sunpa93 — APPROVED** [review]
/lgtm

**Pull request merged**
