### PR TITLE
fix: Workload identity is not working.

### LINKED ISSUE #2229: Workload identity is not working
**What happened**: Workload identity is not working

**What you expected to happen**: Workload identity should work

**How to reproduce it**: Try to use workload identity

**Anything else we need to know?**:

Since this commit: https://github.com/wiz-sec/azuredisk-csi-driver/commit/01b0efc4be6b8963eeff0fcd0c5a35f3edeb5545 workload identity is broken, since ParseConfig is not called anymore and therefore this code part:
```
if tenantID := os.Getenv("AZURE_TENANT_ID"); tenantID != "" {
	config.TenantID = tenantID
}
if clientID := os.Getenv("AZURE_CLIENT_ID"); clientID != "" {
	config.AADClientID = clientID
}
if federatedTokenFile := os.Getenv("AZURE_FEDERATED_TOKEN_FILE"); federatedTokenFile != "" {
	config.AADFederatedTokenFile = federatedTokenFile
	config.UseFederatedWorkloadIdentityExtension = true
}
```
does not get called anymore.

**Environment**:

- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by cvvz**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: Workload identity is not working.
**Which issue(s) this PR fixes**:

Fixes #2229

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
fix: Workload identity is not working.
```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
is there any way to add a test for this? at least adding a ut since this is not covered in e2e test now

**Comment by cvvz** [comment]
> is there any way to add a test for this? at least adding a ut since this is not covered in e2e test now

I've added a ut for running with workload identity test scenario, please take a look.

**Comment by andyzhangx** [comment]
could you squash all commits and then make same fix on other CSI drivers? thanks.

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
