### PR TITLE
[V2] chore: Fixes for E2E testing on CAP-Z clusters

### PR DESCRIPTION
**Pull request by edreed**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

* Properly excludes control-plane nodes from agent node dependent tests.
* Reconciles differences in NodeGetInfo implementation between v1 & v2 drivers.
* Skips block volume tests on Windows.
* Works around kubernetes/kubernetes#104562 using an init container to create a suitable kubeconfig file.
* Adds a Windows cluster configuration for E2E testing with container-d.
* Adds support for testing on Windows Server 2022.

**Which issue(s) this PR fixes**:

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by sunpa93 — APPROVED** [review]
/lgtm

**Comment by edreed** [comment]
Created #1349 for the skipped Windows test.

**Pull request merged**
