### PR TITLE
fix getting instance id failure

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
controller should not depend on `cloud.InstanceID`, remove this dependency.

You may get following error without this PR:
```
I0930 20:58:23.803208       1 controllerserver.go:294] ControllerPublishVolume: called with args {VolumeId:/subscriptions/xxx/resourceGroups/chuwon/providers/Microsoft.Compute/disks/pvc-4f21dcfc-fe49-4100-89e8-68a205a01c97 NodeId:k8s-agentpool1-95854893-1 VolumeCapability:mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER >  Readonly:false Secrets:map[] VolumeContext:map[skuName:Standard_LRS storage.kubernetes.io/csiProvisionerIdentity:1569876755795-8081-disk.csi.azure.com] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
E0930 20:58:23.825534       1 utils.go:117] GRPC error: rpc error: code = NotFound desc = failed to get azure instance id for node "k8s-agentpool1-95854893-1" (Get http://169.254.169.254/metadata/instance?api-version=2019-03-11&format=json: dial tcp 169.254.169.254:80: i/o timeout)
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
fix getting instance id failure
```

/assign @chewong

### CODE REVIEW

**Comment by andyzhangx** [comment]
There is also `cloud.Instances()` invocation on `NodeGetInfo`, looks like I need to remove this dependency also.

```
func (d *Driver) NodeGetInfo(ctx context.Context, req *csi.NodeGetInfoRequest) (*csi.NodeGetInfoResponse, error) {
        klog.V(5).Infof("Using default NodeGetInfo")

        instances, ok := d.cloud.Instances()
        if !ok {
                return nil, status.Error(codes.Internal, "Failed to get instances from cloud provider")
        }

        instanceType, err := instances.InstanceType(context.TODO(), types.NodeName(d.NodeID))
        if err != nil {
                klog.Warningf("Failed to get instance type from Azure cloud provider, nodeName: %v, error: %v", d.NodeID, err)
                instanceType = ""
        }

        if vmSizeList == nil {
                ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
                defer cancel()
                result, err := d.cloud.VirtualMachineSizesClient.List(ctx, d.cloud.Location)
                if err != nil || result.Value == nil {
                        return nil, status.Error(codes.Internal, "failed to list vm sizes in GetVolumeLimits from Azure cloud provider, nodeName: "+d.NodeID)
                }
                vmSizeList = result.Value
        }

        return &csi.NodeGetInfoResponse{
                NodeId:            d.NodeID,
                MaxVolumesPerNode: getMaxDataDiskCount(instanceType, vmSizeList),
        }, nil
}

```

**Comment by chewong** [comment]
@andyzhangx there is another instance metadata service dependency in [`d.cloud.DetachDisk`](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/pkg/azuredisk/controllerserver.go#L378), specifically [here](https://github.com/kubernetes/legacy-cloud-providers/blob/master/azure/azure_controller_common.go#L153) that is still causing a similar `169.254.169.254:80: i/o timeout` error when I run E2E test. I also tried ssh into the agent node and run `curl -H Metadata:true http://169.254.169.254/metadata/instance?api-version=2019-03-11&format=json` and it returns the json result without any error.

**Comment by andyzhangx** [comment]
> 169.254.169.254:80:

I guess there is sth different as csi driver runs as a container, how can I repro this issue? could you provide
 - k8s version
 - how do you deploy csi driver? by helm or deployment script?

**Comment by chewong** [comment]
@andyzhangx I am using k8s v1.16 deployed with aks-engine v0.39.1 using the following kubernetes config
```
"kubernetesConfig": {
    "networkPolicy": "none",
    "cloudProviderRateLimitQPS": 6,
    "cloudProviderRateLimitBucket": 20,
    "controllerManagerConfig": {
        "--feature-gates": "CSIInlineVolume=true,LocalStorageCapacityIsolation=true,ServiceNodeExclusion=true,ServiceLoadBalancerFinalizer=true"
    },
    "apiServerConfig": {
        "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,AlwaysPullImages"
    }
}
```

I deployed the CSI driver built from #166 using Helm. I will try running the E2E tests with `mcr.microsoft.com/k8s/csi/azuredisk-csi:latest` / using k8s v1.15 to see if I have the same problem.

**Comment by andyzhangx** [comment]
> @andyzhangx I am using k8s v1.16 deployed with aks-engine v0.39.1 using the following kubernetes config
> 
> ```
> "kubernetesConfig": {
>     "networkPolicy": "none",
>     "cloudProviderRateLimitQPS": 6,
>     "cloudProviderRateLimitBucket": 20,
>     "controllerManagerConfig": {
>         "--feature-gates": "CSIInlineVolume=true,LocalStorageCapacityIsolation=true,ServiceNodeExclusion=true,ServiceLoadBalancerFinalizer=true"
>     },
>     "apiServerConfig": {
>         "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,AlwaysPullImages"
>     }
> }
> ```
> 
> I deployed the CSI driver built from #166 using Helm. I will try running the E2E tests with `mcr.microsoft.com/k8s/csi/azuredisk-csi:latest` / using k8s v1.15 to see if I have the same problem.

could you try using these scripts to install driver:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/install-csi-driver-master.md
I tried again on my `v1.16.0-alpha.3` cluster, it works well.

**Comment by chewong** [comment]
@andyzhangx do you have `useInstanceMetadata` enabled in your cluster configuration when you tried to run E2E? I am still encountering the same issue `Get http://169.254.169.254/metadata/instance?api-version=2019-03-11&format=json: dial tcp 169.254.169.254:80: i/o timeout` unless I disable `useInstanceMetadata` in the cluster configuration.

**Pull request merged**
