### PR TITLE
fix: invalid ultra disk default iops issue

### LINKED ISSUE #1442: Requesting `iopsPerGB` or `allowAutoIOPSPerGBIncrease ` for ultradisk parameter.
**Is your feature request related to a problem?/Why is this needed**

if your storage class is like below (with ultradisk as the sku name), the default provisioned IOPS for such disk is 500
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: ultra-disk
parameters:
  cachingMode: None
  skuname: UltraSSD_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

```

when you provision a PVC with disksize greater than 500GB it results in the following error.

```json
"statusMessage": "{\"error\":{\"code\":\"BadRequest\",\"message\":\"The value 500 of parameter disk.diskIOPSReadWrite is not valid. The supported range for a UltraSSD_LRS disk of size 512 GB is between 512 and 153600.\"}}",
```

Our pods are in pending and this is affecting our customers from provisioning Ultradisk over 500GB of disk capacity. 

**Describe the solution you'd like in detail**

We need something like `iopsPerGB ` as explained [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/parameters.md) in aws-ebs's driver or a flag like this `allowAutoIOPSPerGBIncrease` that sets a meaningful default IOPS so that Volume mount wont fail. 

can this flag also be mutable to existing StorageClass so that we dont have to create a new storage to support this feature? 

**Describe alternatives you've considered**

**Additional context**

Note: Support request ID	2207310050000344 and affecting our production system right now.

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: invalid ultra disk default iops issue

**Which issue(s) this PR fixes**:

Fixes #1442

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:
this PR tries to fix the following issue:
```
  "error": {
    "code": "BadRequest",
    "message": "The value 500 of parameter disk.diskIOPSReadWrite is not valid. The supported range for a UltraSSD_LRS disk of size 512 GB is between 512 and 153600."
  }
```

**Release note**:
```
fix: invalid ultra disk default iops issue
```

### CODE REVIEW

**Review by dhilipkumars — APPROVED** [review]

**Review by ZeroMagic — APPROVED** [review]
/lgtm

**Pull request merged**
