### PR TITLE
chore: upgrade provisioner to v2.0.4

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
chore: upgrade provisioner to v2.0.4

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by andyzhangx** [comment]
upgrade provisioner to v2.0.4 would break 1.16 since it v2.0.4 requires 1.17 version at least.

**Pull request closed without merging**
