### PR TITLE
Add Unit tests in pkg/azuredisk/controllerserver_test.

### LINKED ISSUE #382: improve unit test coverage
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

improve UT coverage including
 - controllerserver
 - nodeserver
 - identityserver
 - version

https://coveralls.io/github/kubernetes-sigs/azuredisk-csi-driver?branch=master

image

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Sakuralbj**
**What type of PR is this?**

>

 /kind test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #382 

**Special notes for your reviewer**:
I'll add more unit tests after I learn more about gomock and StorageAccountClient .

**Release note**:
```

```

### CODE REVIEW

**Comment by andyzhangx** [comment]
it's 
```
/kind test
```

not 
```
> /kind test
```

**Comment by Sakuralbj** [comment]
> it's
> 
> ```
> /kind test
> ```
> 
> not
> 
> ```
> > /kind test
> ```

Thanks. I will pay attention next time.

**Pull request merged**
