### PR TITLE
chores: format go.mod and bump dependencies

### PR DESCRIPTION
**Pull request by MartinForReal**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
chores: format go.mod and bump dependencies
**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [x] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
how did you make this change? could you provide the steps in the PR? thanks.

**Comment by MartinForReal** [comment]
removed the second and the third require statements
ran go mod tidy and the command failed due to metric package not found
ran go mod graph and found that the failure was due to conflict in version of go.opentelemetry.io/otel
checked the status of k8s.io/component-base and added replace statements. 
Then ran go mod tidy and it worked.

**Comment by MartinForReal** [comment]
related: https://github.com/kubernetes-csi/csi-lib-utils/pull/148

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
