### PR TITLE
Refactor:expose gomock controller in fake object

### PR DESCRIPTION
**Pull request by MartinForReal**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
Refactor:expose gomock controller in fake object
**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by MartinForReal** [comment]
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2131

**Pull request merged**
