### PR TITLE
Migrate from legacy-cloud-provider to cloud-provider-azure

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Migrate from legacy-cloud-provider to cloud-provider-azure

Manually modified files:
```
go.mod
pkg/azuredisk/azure.go
pkg/azuredisk/azure_common_darwin.go
pkg/azuredisk/azure_common_windows.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/fake_mounter.go
pkg/azuredisk/fake_mounter_test.go
pkg/mounter/safe_mounter_unix.go
pkg/mounter/safe_mounter_windows.go
tests/e2e/testsuites/testsuites.go
```
The rest of the changes are auto-generated by `go mod tidy` and `go mod vendor`.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/616

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
pls run `hack/verify-all.sh` to make sure basic tests pass.

**Comment by ZeroMagic** [comment]
/cc @andyzhangx 

Ref: `Build commands` and `Vendoring` sections of the latest [Go Modules Reference](https://golang.org/ref/mod#mod-commands).
>By default, if the go version in go.mod is 1.14 or higher and a vendor directory is present, the go command will act as if -mod=vendor were used. Otherwise, the go command will act as if -mod=mod were used.

>When vendoring is enabled, build commands like go build and go test load packages from the vendor directory instead of accessing the network or the local module cache.

If we use go version 1.14+, in our CI test, `-mod=vendor` will be used and it won't download the necessary packages from network. Then because `sigs.k8s.io/azuredisk-csi-driver` is the main module, the `vendoring` mode is still used in the new directory `csi-test` and the sanity tests in CI fails.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
thanks, would you also do the same change on azure file and blob csi drivers? thanks.

**Comment by andyzhangx** [comment]
> /cc @andyzhangx
> 
> Ref: `Build commands` and `Vendoring` sections of the latest [Go Modules Reference](https://golang.org/ref/mod#mod-commands).
> 
> > By default, if the go version in go.mod is 1.14 or higher and a vendor directory is present, the go command will act as if -mod=vendor were used. Otherwise, the go command will act as if -mod=mod were used.
> 
> > When vendoring is enabled, build commands like go build and go test load packages from the vendor directory instead of accessing the network or the local module cache.
> 
> If we use go version 1.14+, in our CI test, `-mod=vendor` will be used and it won't download the necessary packages from network. Then because `sigs.k8s.io/azuredisk-csi-driver` is the main module, the `vendoring` mode is still used in the new directory `csi-test` and the sanity tests in CI fails.

I solved this issue by using csi-sanity test binary directly: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/626

**Pull request merged**
