### PR TITLE
test: added ZRS versions for dynamic provisioning tests

### PR DESCRIPTION
**Pull request by kassarl**
**What type of PR is this?**

/kind test
**What this PR does / why we need it**:
Creates tests to cover possible scenarios of ZRS usage 
**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
that's duplicating too many test cases, I would suggest writing like this:
```
if current region supports ZRS:
  set StorageClassParameters as {"skuName": "StandardSSD_ZRS"}
```

That would save a bunch of test codes and easier to maintain.

**Comment by kassarl** [comment]
> that's duplicating too many test cases, I would suggest writing like this:
> 
> ```
> if current region supports ZRS:
>   set StorageClassParameters as {"skuName": "StandardSSD_ZRS"}
> ```
> 
> That would save a bunch of test codes and easier to maintain.

In this case, does it matter that the test cases would test either ZRS or standard LRS, and not both?

**Comment by andyzhangx** [comment]
> > that's duplicating too many test cases, I would suggest writing like this:
> > ```
> > if current region supports ZRS:
> >   set StorageClassParameters as {"skuName": "StandardSSD_ZRS"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That would save a bunch of test codes and easier to maintain.
> 
> In this case, does it matter that the test cases would test either ZRS or standard LRS, and not both?

I think it's ok since this test case would be run  multiple times since we have quite a lot of different test pipelines in test-infra, and also ZRS depends on region.

**Pull request closed without merging**
