### PR TITLE
fix: disable networkAccessPolicy on Azure Stack Cloud

### LINKED ISSUE #957: Azure Stack Cloud does not support "NetworkAccessPolicy"
**What happened**:
After [`NetworkAccessPolicy`](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/147734c75445b522f63f75ebb98d159b79954885/pkg/azuredisk/controllerserver.go#L350) is introduced, Azure Stack Cloud throws error when creating managed disk: 
```
I0802 20:39:08.747781   50487 controllerserver.go:290] begin to create azure disk(citest-1627936742) account type(Standard_LRS) rg(mc_uss_e2eaks-nls_redmond) location() size(2) diskZone() maxShares(0)
I0802 20:39:08.747805   50487 azure_managedDiskController.go:88] azureDisk - creating new managed Name:citest-1627936742 StorageAccountType:Standard_LRS Size:2
I0802 20:39:09.019545   50487 azure_armclient.go:308] Received error in sendAsync.send: resourceID: https://management.redmond.ext-n25r1310.masd.stbtest.microsoft.com/subscriptions/9451ca98-98e8-4ba8-b50b-dc7497a07255/resourceGroups/mc_uss_e2eaks-nls_redmond/providers/Microsoft.Compute/disks/citest-1627936742?api-version=2019-03-01, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
  "error": {
    "code": "BadRequest",
    "message": "Could not find member 'networkAccessPolicy' on object of type 'DiskProperties'. Path 'properties.networkAccessPolicy', line 1, position 113.",
    "target": "diskDescription.properties.networkAccessPolicy"
  }
}
```

**What you expected to happen**:
On Azure Stack Cloud, bypass setting networkAccessPolicy.

**How to reproduce it**:
Run sanity or integration test.

**Anything else we need to know?**:
Azure Stack Cloud supports the following API version:
```
            "apiVersions": [
                "2019-11-01",
                "2019-07-01",
                "2019-03-01",
                "2018-09-30",
                "2018-06-01",
                "2018-04-01",
                "2017-03-30"
            ],
```

The `NetworkAccessPolicy` is supported since 2020-06-01.

**Environment**:
- CSI Driver version: v1.5.0
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by songjiaxun**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Disable NetworkAccessPolicy on Azure Stack Cloud because it is not supported on Azure Stack.

**Which issue(s) this PR fixes**:

Fixes #957

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by songjiaxun** [comment]
/assign @andyzhangx
Can we release a minor version including this fix for Azure Stack? Otherwise, the driver won't work on Azure Stack at all. Thanks!

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

**Comment by andyzhangx** [comment]
the code logic is like this, so by default, `options.NetworkAccessPolicy` is empty string, why it would fail on azure stack? do you only need to fix the test failure on azure stack?
```
	if options.NetworkAccessPolicy != "" {
		diskProperties.NetworkAccessPolicy = options.NetworkAccessPolicy
		if options.NetworkAccessPolicy == compute.AllowPrivate {
			if options.DiskAccessID == nil {
				return "", fmt.Errorf("DiskAccessID should not be empty when NetworkAccessPolicy is AllowPrivate")
			}
			diskProperties.DiskAccessID = options.DiskAccessID
		} else {
			if options.DiskAccessID != nil {
				return "", fmt.Errorf("DiskAccessID(%s) must be empty when NetworkAccessPolicy(%s) is not AllowPrivate", *options.DiskAccessID, options.NetworkAccessPolicy)
			}
		}
	}
```

**Comment by songjiaxun** [comment]
> why it would fail on azure stack? do you only need to fix the test failure on azure stack?

Actually, the sanity test and integration test failed on Azure Stack, because even though the field `NetworkAccessPolicy` is empty, an older version API cannot handle the unsupported field in the payload. Thus, the only way to fix this is to remove the `NetworkAccessPolicy` field.

**Comment by andyzhangx** [comment]
> > why it would fail on azure stack? do you only need to fix the test failure on azure stack?
> 
> Actually, the sanity test and integration test failed on Azure Stack, because even though the field `NetworkAccessPolicy` is empty, an older version API cannot handle the unsupported field in the payload. Thus, the only way to fix this is to remove the `NetworkAccessPolicy` field.

@songjiaxun so will this PR would fix this testing failure?

**Comment by songjiaxun** [comment]
Yes, this PR will fix all failures on Azure Stack. > > > why it would fail on azure stack? do you only need to fix the test failure on azure stack?
> 
> > 
> 
> > Actually, the sanity test and integration test failed on Azure Stack, because even though the field `NetworkAccessPolicy` is empty, an older version API cannot handle the unsupported field in the payload. Thus, the only way to fix this is to remove the `NetworkAccessPolicy` field.
> 
> 
> 
> @songjiaxun so will this PR would fix this testing failure?

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
