### PR TITLE
test: use `WaitForFirstConsumer` for in-tree storage driver

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

**What type of PR is this?**

**What this PR does / why we need it**:

/kind failing-test
Fixes test failure in https://testgrid.k8s.io/provider-azure-master-signal#capz-azure-disk.
Explicitly Add `zoned` to storage class parameters based on whether we are testing clusters with AZs or not. We weren't able to attach disks to non-AZ worker nodes created by an AZ-enabled master node.

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
`zoned` is not a parameter in csi driver now, try use `volumeBindingMode: WaitForFirstConsumer` instead:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/topology#use-following-storage-class-with-topology-support

**Comment by chewong** [comment]
> `zoned` is not a parameter in csi driver now, try use `volumeBindingMode: WaitForFirstConsumer` instead:
> https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/topology#use-following-storage-class-with-topology-support

Is `zoned` used by in-tree storage driver? The problem with CAPZ clusters right now is that the control plane machines are automatically backed by AZs but the worker nodes aren't. So when kube-controller-manager provisions a disk with an AZ, it isn't able to attach to the worker nodes.

**Comment by andyzhangx** [comment]
> volumeBindingMode: WaitForFirstConsumer

@chewong try use `volumeBindingMode: WaitForFirstConsumer` for in-tree driver, it should work.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Comment by chewong** [comment]
retest

**Pull request merged**
