### PR TITLE
test: support Win2022 test on capz

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
test: support Win2022 test on capz

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by marosset** [comment]
from https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/1280/pull-azuredisk-csi-driver-e2e-capz-windows-2022/1514081085569372160/artifacts/management-cluster/resources/machines.log

```
    message: 'virtualmachine failed to create or update. err: failed to create resource
        capz-8hg1or/capz-8hg1-4nctj (service: virtualmachine): compute.VirtualMachinesClient#CreateOrUpdate:
        Failure sending request: StatusCode=404 -- Original Error: Code="PlatformImageNotFound"
        Message="The platform image ''cncf-upstream:capi-windows:k8s-1dot22dot1-windows-2022-containerd:latest''
        is not available. Verify that all fields in the storage profile are correct.
        For more details about storage profile information, please refer to https://aka.ms/storageprofile"
        Target="imageReference"'
```

We don't have a 1.22.1 image for windows server 2022 / containerd.
The first windows server 2022 / containerd image we have is for 1.22.2.

```bash
az vm image list-skus -p cncf-upstream -f capi-windows -l westus2 | grep containerd

westus2     k8s-1dot22dot1-windows-2019-containerd
westus2     k8s-1dot22dot2-windows-2019-containerd
westus2     k8s-1dot22dot2-windows-2022-containerd
westus2     k8s-1dot22dot3-windows-2019-containerd
westus2     k8s-1dot22dot3-windows-2022-containerd
westus2     k8s-1dot22dot4-windows-2019-containerd
westus2     k8s-1dot22dot4-windows-2022-containerd
westus2     k8s-1dot22dot5-windows-2019-containerd
westus2     k8s-1dot22dot5-windows-2022-containerd
westus2     k8s-1dot22dot6-windows-2019-containerd
westus2     k8s-1dot22dot6-windows-2022-containerd
westus2     k8s-1dot22dot7-windows-2019-containerd
westus2     k8s-1dot22dot7-windows-2022-containerd
westus2     k8s-1dot22dot8-windows-2019-containerd
westus2     k8s-1dot22dot8-windows-2022-containerd
westus2     k8s-1dot23dot0-windows-2019-containerd
westus2     k8s-1dot23dot0-windows-2022-containerd
westus2     k8s-1dot23dot1-windows-2019-containerd
westus2     k8s-1dot23dot1-windows-2022-containerd
westus2     k8s-1dot23dot2-windows-2019-containerd
westus2     k8s-1dot23dot2-windows-2022-containerd
westus2     k8s-1dot23dot3-windows-2019-containerd
westus2     k8s-1dot23dot3-windows-2022-containerd
westus2     k8s-1dot23dot4-windows-2019-containerd
westus2     k8s-1dot23dot4-windows-2022-containerd
westus2     k8s-1dot23dot5-windows-2019-containerd
westus2     k8s-1dot23dot5-windows-2022-containerd
```

We need to set the env var `KUBERNETES_VERSION` to something newer than 1.22.1 in the PROW config.
@CecileRobertMichon @mboersma - would it be safe to use `KUBERNETES_VERSION=latest-1.23` in PROW jobs that use `ci-entrypoint.sh` or could we run into issues if a new 1.23.x patch release comes out and we do not yet have VHDs published for that release?

if it isn't safe should we just set it to 1.23.5 and remember to update it?

**Comment by andyzhangx** [comment]
@marosset sometimes creating a Win 2022 cluster would fail:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/1280/pull-azuredisk-csi-driver-e2e-capz-windows-2022/1514157508187394048/build-log.txt
```
# Get kubeconfig and store it locally.
kubectl get secrets capz-0mxwn2-kubeconfig -o json | jq -r .data.value | base64 --decode > ./kubeconfig
timeout --foreground 600 bash -c "while ! kubectl --kubeconfig=./kubeconfig get nodes | grep control-plane; do sleep 1; done"
error: the server doesn't have a resource type "nodes"
```

**Comment by andyzhangx** [comment]
also I see `kube-proxy-windows` is crashing on Win 2022 node @marosset 

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/1280/pull-azuredisk-csi-driver-e2e-capz-windows-2022/1514170214541955072

```
kube-proxy-windows-qkb68                                  0/1     ImagePullBackOff   0             62m   10.1.0.5        capz-vpcs-7jn54                   <none>           <none>
kube-proxy-windows-vbb4b                                  0/1     ImagePullBackOff   0             62m   10.1.0.4        capz-vpcs-lzddr                   <none>           <none>
```

**Comment by marosset** [comment]
> also I see `kube-proxy-windows` is crashing on Win 2022 node @marosset
> 
> https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/1280/pull-azuredisk-csi-driver-e2e-capz-windows-2022/1514170214541955072
> 
> ```
> kube-proxy-windows-qkb68                                  0/1     ImagePullBackOff   0             62m   10.1.0.5        capz-vpcs-7jn54                   <none>           <none>
> kube-proxy-windows-vbb4b                                  0/1     ImagePullBackOff   0             62m   10.1.0.4        capz-vpcs-lzddr                   <none>           <none>
> ```
> 
> ```
> kube-proxy-windows-qkb68                                  0/1     ImagePullBackOff
> Back-off pulling image "sigwindowstools/kube-proxy:1.23.5-calico-hostprocess"
> ```

Looking

**Comment by marosset** [comment]
> > also I see `kube-proxy-windows` is crashing on Win 2022 node @marosset
> > https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/1280/pull-azuredisk-csi-driver-e2e-capz-windows-2022/1514170214541955072
> > ```
> > kube-proxy-windows-qkb68                                  0/1     ImagePullBackOff   0             62m   10.1.0.5        capz-vpcs-7jn54                   <none>           <none>
> > kube-proxy-windows-vbb4b                                  0/1     ImagePullBackOff   0             62m   10.1.0.4        capz-vpcs-lzddr                   <none>           <none>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > kube-proxy-windows-qkb68                                  0/1     ImagePullBackOff
> > Back-off pulling image "sigwindowstools/kube-proxy:1.23.5-calico-hostprocess"
> > ```
> 
> Looking

We have never produced kube-proxy images with tags containing `-calico-hostprocess`.
I believe this should be `-nanoserver` and is `-calico-host` process due to a mistake that has never be uncovered before (and other CAPZ templates do use `-nanoserver` which exists).

Let me try and address this in CAPZ.

**Comment by marosset** [comment]
> > > also I see `kube-proxy-windows` is crashing on Win 2022 node @marosset
> > > https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/1280/pull-azuredisk-csi-driver-e2e-capz-windows-2022/1514170214541955072
> > > ```
> > > kube-proxy-windows-qkb68                                  0/1     ImagePullBackOff   0             62m   10.1.0.5        capz-vpcs-7jn54                   <none>           <none>
> > > kube-proxy-windows-vbb4b                                  0/1     ImagePullBackOff   0             62m   10.1.0.4        capz-vpcs-lzddr                   <none>           <none>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > kube-proxy-windows-qkb68                                  0/1     ImagePullBackOff
> > > Back-off pulling image "sigwindowstools/kube-proxy:1.23.5-calico-hostprocess"
> > > ```
> > 
> > 
> > Looking
> 
> We have never produced kube-proxy images with tags containing `-calico-hostprocess`. I believe this should be `-nanoserver` and is `-calico-host` process due to a mistake that has never be uncovered before (and other CAPZ templates do use `-nanoserver` which exists).
> 
> Let me try and address this in CAPZ.

nevermind, it looks like we do have `-calico-hostprocess` images. 
https://hub.docker.com/layers/kube-proxy/sigwindowstools/kube-proxy/v1.23.5-calico-hostprocess/images/sha256-0f8a44b795d1824358f24cc56f0024d18a39ae044656686596d8b7fa6d78e1fa?context=explore

These images are based on windows server 2019 / 1809 but that shouldn't be an issue for host-process containers.
I'm still not sure what is going on yet.

**Comment by marosset** [comment]
> > > > also I see `kube-proxy-windows` is crashing on Win 2022 node @marosset
> > > > https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/1280/pull-azuredisk-csi-driver-e2e-capz-windows-2022/1514170214541955072
> > > > ```
> > > > kube-proxy-windows-qkb68                                  0/1     ImagePullBackOff   0             62m   10.1.0.5        capz-vpcs-7jn54                   <none>           <none>
> > > > kube-proxy-windows-vbb4b                                  0/1     ImagePullBackOff   0             62m   10.1.0.4        capz-vpcs-lzddr                   <none>           <none>
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > > kube-proxy-windows-qkb68                                  0/1     ImagePullBackOff
> > > > Back-off pulling image "sigwindowstools/kube-proxy:1.23.5-calico-hostprocess"
> > > > ```
> > > 
> > > 
> > > Looking
> > 
> > 
> > We have never produced kube-proxy images with tags containing `-calico-hostprocess`. I believe this should be `-nanoserver` and is `-calico-host` process due to a mistake that has never be uncovered before (and other CAPZ templates do use `-nanoserver` which exists).
> > Let me try and address this in CAPZ.
> 
> nevermind, it looks like we do have `-calico-hostprocess` images. https://hub.docker.com/layers/kube-proxy/sigwindowstools/kube-proxy/v1.23.5-calico-hostprocess/images/sha256-0f8a44b795d1824358f24cc56f0024d18a39ae044656686596d8b7fa6d78e1fa?context=explore
> 
> These images are based on windows server 2019 / 1809 but that shouldn't be an issue for host-process containers. I'm still not sure what is going on yet.

I am pretty sure the kube-proxy image pull issue is just dockerhub rate-limiting :(
I was able to set up a v1.23.5 cluster running Windows Server 2022 using ci-entrypoint.sh and kube-proxy images all pulled and started succesfully.

**Comment by marosset** [comment]
I took another look after the reties failed.

The issue with the kube-proxy images is actually caused by a missing v
The image reference is supposed to be [sigwindowstools/kube-proxy:v1.23.5-calico-hostprocess](https://hub.docker.com/layers/kube-proxy/sigwindowstools/kube-proxy/v1.23.5-calico-hostprocess/images/sha256-0f8a44b795d1824358f24cc56f0024d18a39ae044656686596d8b7fa6d78e1fa?context=explore) but is `sigwindowstools/kube-proxy:1.23.5-calico-hostprocess`
I can try and fix that in CAPZ 

I am still not sure why the e2e tests are failing tho...

**Comment by andyzhangx** [comment]
> I took another look after the reties failed.
> 
> The issue with the kube-proxy images is actually caused by a missing v The image reference is supposed to be [sigwindowstools/kube-proxy:v1.23.5-calico-hostprocess](https://hub.docker.com/layers/kube-proxy/sigwindowstools/kube-proxy/v1.23.5-calico-hostprocess/images/sha256-0f8a44b795d1824358f24cc56f0024d18a39ae044656686596d8b7fa6d78e1fa?context=explore) but is `sigwindowstools/kube-proxy:1.23.5-calico-hostprocess` I can try and fix that in CAPZ
> 
> I am still not sure why the e2e tests are failing tho...

@marosset thanks, current win 2022 tests are not stable, there are always one or two different cases failed with `KillPodSandboxError`, looks like it's win 2022 stability issue not related to disk driver.

```
Apr 14 06:04:36.408: INFO: At 2022-04-14 05:56:16 +0000 UTC - event for azuredisk-volume-tester-59m9v: {kubelet capz-0my2-bps4g} Created: Created container volume-tester
Apr 14 06:04:36.408: INFO: At 2022-04-14 05:58:16 +0000 UTC - event for azuredisk-volume-tester-59m9v: {kubelet capz-0my2-bps4g} Failed: Error: context deadline exceeded
Apr 14 06:04:36.408: INFO: At 2022-04-14 05:58:16 +0000 UTC - event for azuredisk-volume-tester-59m9v: {kubelet capz-0my2-bps4g} Pulled: Container image "mcr.microsoft.com/windows/servercore:ltsc2022" already present on machine
Apr 14 06:04:36.408: INFO: At 2022-04-14 05:58:22 +0000 UTC - event for azuredisk-volume-tester-59m9v: {kubelet capz-0my2-bps4g} Started: Started container volume-tester
Apr 14 06:04:36.408: INFO: At 2022-04-14 05:58:22 +0000 UTC - event for azuredisk-volume-tester-59m9v: {kubelet capz-0my2-bps4g} Killing: Stopping container volume-tester
Apr 14 06:04:36.408: INFO: At 2022-04-14 06:00:24 +0000 UTC - event for azuredisk-volume-tester-59m9v: {kubelet capz-0my2-bps4g} FailedKillPod: error killing pod: failed to "KillPodSandbox" for "6b93ade4-7c36-4244-87b5-62fa24c3cb74" with KillPodSandboxError: "rpc error: code = DeadlineExceeded desc = context deadline exceeded"
```

Another question, currently all capz windows tests will set up 1 master node, 2 Linux nodes, 2 Windows nodes, do you know how to remove the `2 Linux nodes` since it's not necessary in e2e test, that could save cost. Thanks.

**Comment by andyzhangx** [comment]
amazing, `pull-azuredisk-csi-driver-e2e-capz-windows-2022` tests all pass, need a few more runs to make sure it's stable enough, then I will set this test as mandaory, thanks @marosset

**Pull request merged**
