### PR TITLE
test: migrate azureclient to track2 sdk in e2e test suite

### PR DESCRIPTION
**Pull request by MartinForReal**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [x] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
so this PR only changes the e2e test client, it does not touch the driver functionality code now, right? @MartinForReal

**Comment by MartinForReal** [comment]
Yes! @andyzhangx

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
