### PR TITLE
Refactor: load config with configloader

### PR DESCRIPTION
**Pull request by MartinForReal**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Refactor: load config with configloader
**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by MartinForReal** [comment]
<html>
<body>

/test pull-azuredisk-csi-driver-e2e-capz-windows-2019
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by andyzhangx** [comment]
thanks, it works, could you make same change on azure file and blob csi drivers, thanks!

**Pull request merged**
