### PR TITLE
chore: Remove unnecessary permissions from external-snapshotter role.

### LINKED ISSUE #581: Improve csi-snapshotter ClusterRole
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

With v2.0.0 of kubernetes-csi/external-snapshotter, it is split into two component - the csi-snapshotter sidecar and the snapshot controller (ref kubernetes-csi/external-snapshotter#182). As the VolumeSnapshot watch is moved to the new snapshot controller, the csi-snapshotter sidecar ClusterRole no longer needs rules for volumesnapshots.
This PR adapts the csi-snapshotter sidecar RBAC according to https://github.com/kubernetes-csi/external-snapshotter/blob/v2.1.1/deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml.

refer to https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/491

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by edreed**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

With v2.0.0 of kubernetes-csi/external-snapshotter, it is split into two component - the csi-snapshotter sidecar and the snapshot controller (ref kubernetes-csi/external-snapshotter#182). As the VolumeSnapshot watch is moved to the new snapshot controller, the csi-snapshotter sidecar ClusterRole no longer needs rules for volumesnapshots.
This PR adapts the csi-snapshotter sidecar RBAC according to https://github.com/kubernetes-csi/external-snapshotter/blob/v2.1.1/deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml.

refer to kubernetes-sigs/aws-ebs-csi-driver#491

**Which issue(s) this PR fixes**:

Fixes #581 

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by edreed** [comment]
In addition to running "make verify", I manually tested the change by running through the steps outlined in https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/snapshot/README.md.

**Comment by andyzhangx** [comment]
thanks, could you also make changes under `charts` dir in same file?

**Comment by edreed** [comment]
I updated the file in charts/latest and manually verified the changed.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
