### PR TITLE
feat: add dataAccessAuthMode parameter to snapshot storage class

### LINKED ISSUE #1702: Add dataAccessAuthMode parameter to snapshot
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Need an option to enable AAD on snapshots taken through CSI driver.
image

Parameter inside Snapshot JSON 
      "dataAccessAuthMode": "AzureActiveDirectory",

https://learn.microsoft.com/en-us/rest/api/compute/disks/create-or-update?tabs=HTTP#dataaccessauthmode

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
feat: add dataAccessAuthMode parameter to snapshot storage class

**Which issue(s) this PR fixes**:

Fixes #1702

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
feat: add dataAccessAuthMode parameter to snapshot storage class
```

### CODE REVIEW

**Comment by anshulahuja98** [comment]
Hi @andyzhangx  would you be doing similar changes in the V2 driver?

**Comment by andyzhangx** [comment]
> Hi @andyzhangx would you be doing similar changes in the V2 driver?

@edreed will do the porting work to v2 driver.

**Comment by anshulahuja98** [comment]
okay thanks for the confirmation!

**Pull request merged**
