### PR TITLE
[V2] test: Enable dynamically provisioned volume snapshot test in Windows cluster

### PR DESCRIPTION
**Pull request by alice-zheyan-yu**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
Add more tests to make our code more robust.

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@alice-zheyan-yu can you also enable this test on v1 driver in `master` branch? thanks.

**Comment by alice-zheyan-yu** [comment]
> 

@andyzhangx Yes, I'll do it.

**Pull request merged**
