### PR TITLE
chore: increase csi-attacher timeout

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
chore: increase csi-attacher timeout
This PR also cleaned up preview deployments

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by AnishShah** [comment]
@andyzhangx , is there a reason for such a large timeout of 1200 seconds ?

**Comment by andyzhangx** [comment]
> @andyzhangx , is there a reason for such a large timeout of 1200 seconds ?

@AnishShah in P99, there are cases that disk attach costs > 1200s

**Comment by andyzhangx** [comment]
@AnishShah any other concern on this change?

**Comment by AnishShah** [comment]
We are running OSS k8s storage tests against our Azure cluster (non-AKS). Our tests are failing with timeouts. On investigation, we noticed Azure API timeouts in azuredisk logs. So I'm investigating if we need to increase the timeout duration in our config.

**Pull request merged**
