### PR TITLE
test: print out driver logs

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
test: print out driver logs for external e2e tests

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
`pull-azuredisk-csi-driver-external-e2e-single-az` should fail if external storage e2e tests failed, would you fix this? @boddumanohar 

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/809/pull-azuredisk-csi-driver-external-e2e-single-az/1387298770214981632

```
{"msg":"FAILED External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand should resize volume when PVC is edited while pod is using it","total":20,"completed":0,"skipped":77,"failed":1,"failures":["External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand should resize volume when PVC is edited while pod is using it"]}
skipped 62 lines unfold_more
Apr 28 07:04:41.949: INFO: PersistentVolumeClaim disk.csi.azure.com5754p found and phase=Bound (4.105445308s)
STEP: Creating a pod with dynamically provisioned volume
STEP: Expanding current pvc
Apr 28 07:05:18.147: INFO: currentPvcSize {{1048576 0} {<nil>} 1Mi BinarySI}, newSize {{1074790400 0} {<nil>}  BinarySI}
STEP: Waiting for cloudprovider resize to finish
Apr 28 07:15:18.316: FAIL: While waiting for pvc resize to finish
Unexpected error:
    <*errors.errorString | 0xc0037907d0>: {
        s: "error while waiting for controller resize to finish: timed out waiting for the condition",
    }
    error while waiting for controller resize to finish: timed out waiting for the condition
occurred
Full Stack Trace
k8s.io/kubernetes/test/e2e/storage/testsuites.(*volumeExpandTestSuite).DefineTests.func6()
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go:269 +0xa1d
skipped 148 lines unfold_more
Latency metrics for node k8s-master-31652082-0
Apr 28 07:15:36.525: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "volume-expand-7213" for this suite.
• Failure [659.069 seconds]
External Storage [Driver: disk.csi.azure.com]
/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/external/external.go:169
  [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand
  /workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:126
    should resize volume when PVC is edited while pod is using it [Measurement]
    /workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go:232
    Apr 28 07:15:18.316: While waiting for pvc resize to finish
      
    Unexpected error:
        <*errors.errorString | 0xc0037907d0>: {
            s: "error while waiting for controller resize to finish: timed out waiting for the condition",
        }
        error while waiting for controller resize to finish: timed out waiting for the condition
    occurred
    /workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go:269
------------------------------
{"msg":"FAILED External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand should resize volume when PVC is edited while pod is using it","total":14,"completed":0,"skipped":216,"failed":1,"failures":["External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand should resize volume when PVC is edited while pod is using it"]}
skipped 945 lines unfold_more
[Fail] External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand [Measurement] should resize volume when PVC is edited while pod is using it 
/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go:269
Ran 20 of 5426 Specs in 1130.253 seconds
FAIL! -- 18 Passed | 2 Failed | 0 Pending | 5406 Skipped 
```

**Comment by andyzhangx** [comment]
and after the test script fix, I will disable following 2 test cases which are expected to fail:
```
[91m[1mSummarizing 2 Failures:[0m

[91m[1m[Fail] [0m[90mExternal Storage [Driver: disk.csi.azure.com] [0m[0m[Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand [0m[91m[1m[Measurement] should resize volume when PVC is edited while pod is using it [0m
[37m/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go:269[0m

[91m[1m[Fail] [0m[90mExternal Storage [Driver: disk.csi.azure.com] [0m[0m[Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand [0m[91m[1m[Measurement] should resize volume when PVC is edited while pod is using it [0m
[37m/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go:269[0m
```

**Comment by boddumanohar** [comment]
taking a look.

**Pull request merged**
