### PR TITLE
test: add in-tree-migration.json

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
This PR add in-tree-migration.json for migration from in-tree driver to CSI driver. Later, we also need to add following config, while following config depends on https://github.com/kubernetes/kubernetes/pull/88014 which is merged in `v1.18.0-beta.0`, `v1.17.4`, so I would make following config change when we switched to use `v1.18.0`. In current stage, let's use this config.
```
"kubernetesConfig": {
    "kubeletConfig": {
        "--feature-gates": "CSIMigration=true,CSIMigrationAzureDisk=true"
    }
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/assign @chewong 

**Release note**:
```
none
```

### CODE REVIEW

**Comment by chewong** [comment]
Are we running e2e test on this cluster configuration without building and installing the driver?

**Comment by andyzhangx** [comment]
> Are we running e2e test on this cluster configuration without building and installing the driver?

@chewong you are right, migration tests should run in cluster with our csi driver installed, with in-tree driver storage class. Let me change the PR a little.

**Comment by andyzhangx** [comment]
@chewong I have verified that with following aks-engine cluster definition, basic test on in-tree azure disk driver to csi driver works well on `1.18.0-beta.1`, `1.17.4` should also works well.

```
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.18.0-beta.1",
      "kubernetesConfig": {
         "controllerManagerConfig": {
           "--feature-gates": "CSIInlineVolume=true,LocalStorageCapacityIsolation=true,ServiceNodeExclusion=true,CSIMigration=true,CSIMigrationAzureDisk=true"
         },
        "kubeletConfig": {
          "--feature-gates": "CSIMigration=true,CSIMigrationAzureDisk=true"
        }
      }
    },
```

**Comment by chewong** [comment]
I will start setting the presubmit job.

**Pull request merged**
